name       : python-pytest-isort
version    : 2.0.0
release    : 4
source     :
    - https://github.com/stephrdev/pytest-isort/archive/refs/tags/2.0.0.tar.gz : 2b6ca4d0a5fbf49709de8305008d8bea7d1ae77f4e675bbac0171269cda0500c
homepage   : https://github.com/moccu/pytest-isort
license    : BSD-3-Clause
component  : programming.python
summary    : py.test plugin to check import ordering using isort
description: |
    py.test plugin to check import ordering using isort
builddeps  :
    - python-isort
    - python-pytest
rundeps    :
    - python-isort
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
   %python3_test pytest3 -v
