name       : python-pytest-isort
version    : 3.1.0
release    : 5
source     :
    - https://github.com/stephrdev/pytest-isort/archive/refs/tags/3.1.0.tar.gz : c6994dd442e2fe50f2667d6fa6e14a5800192966b628cc31107c8f96c36a514b
homepage   : https://github.com/moccu/pytest-isort
license    : BSD-3-Clause
component  : programming.python
summary    : py.test plugin to check import ordering using isort
description: |
    py.test plugin to check import ordering using isort
builddeps  :
    - python-build
    - python-installer
    - python-isort     # check
    - python-poetry
    - python-pytest    # check
rundeps    :
    - python-isort
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
